─ DEMO.DESIGN.UUE (2:5021/22) ─────────────────────────────── DEMO.DESIGN.UUE ─
 Msg  : 3566 of 8128
 From : Ivan Misuno                         2:5020/400      12 Oct 98  02:36:12
 To   : All                                                 13 Oct 98  04:41:47
 Subj : Re: <~200b intros
───────────────────────────────────────────────────────────────────────────────
From: "Ivan Misuno (QD)" <qdamage@chat.ru>

Andrey Romanov пишет в сообщении <908073900@p10.f13.n5052.z2.ftn> ...
по приколу "<~200b intros" :
>Поделитесь, если не жалко, коллекцией интересных subj.
>Или эти шедевры редкость? Можно URL.

вот...
одна UniVerse'вская
(имхо глюк -- нажми pause, но выглядит круто  :))
и две мои -- так, по приколу...
а вообще у меня немеряно их -- с Hornet'a слил

ну, хоп !
--
*** Vano @ Quad Damage *** ICQ# 16665834 *** http://qdamage.webjump.com ***
*** темы нет, есть только по-приколу ***




--- ifmail v.2.14dev2
 * Origin: Quad Damage Team (2:5020/400@fidonet)

