; Структура тэгов такая:
; "начало тэга"
; "как заменить тэг"
; "как закрыть тэг"

[TAGS]
"u", "u", "/u"
"i", "i", "/i"
"b", "b", "/b"
"email", "a href=\"mailto:%s\"", "/a"
"url", "a href=\"%s\"", "/a"
"hr", "hr width=80%", "/hr"
"hilight", "table bgcolor=\"#eeeeee\" width=\"98%\"><tr><td bgcolor=\"#fafafa\"><font size=\"-1\"face=\"Courier New\"", "/font></td></tr></table"
"table", "table", "/table"
"tr", "tr", "/tr"
"td", "td", "/td"
"center", "center", "/center"
"right", "div align=\"right\"", "/div"
"left", "div align=\"left\"", "/div"
"justify", "div align=\"justify\"", "/div"
"big", "big", "/big"
"small", "small", "/small"
"blockquote", "blockquote", "/blockquote"
"size", "size", "/size"
"nobr", "nobr", "/nobr"
"sub", "sub", "/sub"
"sup", "sup", "/sup"
"tt", "tt", "/tt"
"strong", "strong", "/strong"
"em", "em", "/em"
"cite", "cite", "/cite"
"abbr", "abbr", "/abbr"
"acronym", "acronym", "/acronym"
"samp", "samp", "/samp"
"var", "var", "/var"
"ul", "ul", "/ul"
"ol", "ol", "/ol"
"li", "li", "/li"
"code", "code", "/code"

[TAGS WITH STRINGS INSIDE]
"url=%s", "a href=\"%s\"", "/a"
"email=%s", "a href=\"mailto:%s\"", "/a"
"h%s", "h%s", "/h%s"
"img=%s", "img src=\"%s\"", "/img"
"table width=%s", "table width=%s%%", "/table"
"table border=%s", "table border=%s", "/table"
"td widht=%s", "td width=\"%s\"", "/td"
"td bgcolor=#%s", "td bgcolor=#%s", "/td"
"td bgcolor=%s", "td bgcolor=%s", "/td"
"ol=%s", "ol start=\"%s\"", "/ol"

[COLORS]
comment		0x008000
string		0xff00ff
number		0x0000ff
skobka		0x0000ff
operator	0x0000ff
macro		0x000080
init		0x800000

[COMMENTS]
Open /*
Close */
String //

[HILIGHTS]
auto
break
bool
case
char
const
comment
continue
defined
default
do
double
else
enum
extern
float
for
goto
if
int
long
register
return
short
signed
sizeof
static
struct
switch
typedef
union
unsigned
void
volatile
while

__asm
__based
__cdecl
__declspec
__except
__far
__fastcall
__finally
__fortran
__huge
__inline
__int16
__int32
__int64
__int8
__interrupt
__leave
__loadds
__near
__pascal
__saveregs
__segment
__segname
__self
__stdcall
__try
__uuidof

#define
#error
#include
#elif
#if
#line
#else
#ifdef
#pragma
#endif
#ifndef
#undef

catch
class
const_cast
data_seg
delete
dynamic_cast
explicit
_export
false
friend
inline
mutable
new
namespace
operator
private
protected
public
reinterpret_cast
static_cast
template
this
throw
true
try
typeid
typename
using
virtual
wchar_t

__multiple_inheritance
__single_inheritance
__virtual_inheritance
dllexport
dllimport
naked
uuid