#---------------------------------
# Administrator Configuration File
#---------------------------------

#$script="/cgi-bin/news/news.cgi";	# Script URL
$newsfile="./news.db";			# News database file
$archivetemplate = './newsarc.tpl';	# Arhive page template

# --- News Formatting -----
# <newsdate>  = date & time
# <newslink>  = news link (URL)
# <newsimg>   = simple image url
# <newstitle> = news title
# <newstext>  = news text
# <newsimage> = IMAGE TAG ! 
# <more>      = news "more" string with a link to document


$GMT=2;			# Time offset


$showtime=0;		# If time required

#$maxnews=15;		# News per page
$maxnews=10;		# News per page

# Template for each news
$newstemplate=qq~
      <tr valign="top">
        <td width="35">
	<newsdate>&nbsp;
	</td>
<!--
        <td valign="bottom" class="colon"><a class="blue"
        href="<newslink>"><b><p id="t<num>"><newstitle></p></b></a>
        <td class="colon"><p id="p<num>"><newstext></p></td>
-->
        <td class="colon">
        <div class="news-title">
	<a href="<newslink>"><newstitle></a>
	</div>
	<newstext>
	</td>
      </tr>
~;

# Template for "MORE INFO..."
$moretemplate=qq~   <a href="<link>" class="mbtxt" title="Читать дальше...">Подробнее<img src="/images/podr.gif" alt="" width="20" height="10" border="0"></a>~; 

# Template for images
$imgtemplate=qq~<a href="<link>"><img src="<img>" alt="Подробнее..." border="0"></a>~;   

1;
