From network
From: "Shayde/Reality" <>
Date: Tue, 01 Feb 1995
Subject: RAD 1.0a - Reality ADlib Tracker
X-Filename: radv1_0a.zip

{>$About}
Assembler source code for <br>
RAD v1.0a - The COMPLETE Adlib Package. <br>
* FULLY functional ADLIB Tracker <br>
* ASM SOURCE Play-Routine included <br>
* HSC & Screamtracker ADLIB support
{>$Description}

    Welcome to the wonderful world of...

 ллллллллллллллллллллллм      ммллллллллллллллллмм    лллллллллллллллллллллмм
  ллллллллллллппппппллллл    лллллллллллллппппллллл   плллллллллллллпппппллллл
  ллллллллллллллллллллллп   лллллллллллллллллллллллл   ллллллллллллл      ллллл
  лллллллллллл      ллллл   ллллллллллллл      ллллл   ллллллллллллл     мллллл
 лллллллллллллл    ллллллл ллллллллллллллл    ллллллл ллллллллллллллллллллллллл
 лллллллллллллл    ллллллл ллллллллллллллл    ллллллл лллллллллллллллллллллллл
 лллллллллллллл    ллллллл ллллллллллллллл    ллллллл лллллллллллллллллллллпп

 ФФФФФФФФФФФФ ФФ Ф љњ Reality ADlib Tracker  Version 1.0a њљ Ф ФФ ФФФФФФФФФФФФ
                            [Released February 1995]

    This archive should contain the following files:


    FILE             DESCRIPTION
    ~~~~             ~~~~~~~~~~~
    RAD.EXE          The RAD tracker
    RAD.DOC          Documentation for RAD

    ADLIBSP.RAD
    CRYSTAL2.RAD
    HANGOVER.RAD
    HUBBARD.RAD      \
    NEOINTRO.RAD       Collection of RAD module files in TUNES.ZIP
    REVENGE.RAD      /
    SHOOT.RAD
    SMJOOP.RAD
    SP2.RAD
    WVCHILD.RAD

    RADPLAY.EXE      A simple DOS RAD player

    PLAYER.ASM       Source-code for playing RAD tunes in your productions.
    RADTEST.ASM      Source-code demonstrating the use of PLAYER.ASM
    RADTEST.EXE      Assembled version of RADTEST.ASM that plays HANGOVER
                     tune by Void/Reality.  (Crunched)
    HANGOVER.INC     Data file used by RADTEST.ASM
    MAKETEST.BAT     A batch file that assembles and links RADTEST (assumes
                     TASM 4.0 and TLINK).

    FILE_ID.DIZ      Gee....I can't figure it out...! :-)
    README.TXT       You surely couldn't be THAT slow! ;-)


                 њ Ф ФФ We hope you enjoy using RAD! ФФ Ф њ


L8'er!

REALITY PRODUCTIONS - February 1995
