<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: vot
 * Date: Wed, 23 Aug 2006 12:13:33 +0400
 */

$conf['mediadir'] = '/usr/local/www/votsrc/htdocs';
$conf['title'] = 'Исходники.Ру';
$conf['lang'] = 'ru';
$conf['template'] = 'sidebar';
$conf['start']       = 'index';           //name of start page
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useheading'] = 1;
$conf['allowdebug'] = 0;
$conf['usewordblock'] = 0;
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['resendpasswd'] = 1;
//$conf['superuser'] = 'vot';
$conf['superuser']   	= '@admin';
$conf['profileconfirm'] = 0;
$conf['usegzip'] = 0;
$conf['compress'] = 0;
$conf['charset'] = 'windows-1251';

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
