#---------------------------------
# Administrator Configuration File
#---------------------------------

#$script="/cgi-bin/admin/admin.cgi";	# Script URL

$newsfile="../news/news.db";		# News database file

#$rootdir = "../../";         		# HTML root directory

#$imagesdir = "../../htdocs/images";     # Images directory

$templatefile="./news.tpl";		# Page Template file

#$moderatorsfile = "./news.mod";		# News Moderators logins/passwords

# --- News Formatting -----
# <newsdate>  = date & time
# <newslink>  = news link (URL)
# <newsimg>   = simple image url
# <newstitle> = news title
# <newstext>  = news text
# <newsimage> = IMAGE TAG ! 
# <more>      = news "more" string with a link to document


$GMT=2;			# Time offset


$showtime=0;		# If time required

$maxnews=15;		# News per page

# Template for each news
$newstemplate=qq~
      <tr>
        <td width="35"><font face="Tahoma" style="font-size: 8pt" size="-1"><newsdate>&nbsp;</font> </td>
        <td valign="bottom" class="colon"><a class="blue"
        href="<newslink>"><b><p id="t<num>"><newstitle></p></b></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td class="colon"><p id="p<num>"><newstext></p></td>
      </tr>
~;

# Template for edit news
$edittemplate=qq~
      <subtext>
        <tr>
          <td colspan=2>
      <table cellspacing="0" cellpadding="1" border="0" width="100%" bgcolor="#cccccc">
        <tr>
          <td valign="top">
            <table cellspacing="0" cellpadding="4" border="0" width="100%">
              <tr bgcolor="#ffffff">
                <td valign="top">
                  <input type=hidden name=num value="<num>">
                  <b>Время/дата:</b>
                  <br><input type=text name=date size=20 value="<newsdate>">
                  <br><b>Заголовок:</b>
                  <br><input type=text name=title size=80 value="<newstitle>">
                  <br><b>Текст:</b>
                  <br><textarea name=text cols=80 rows=10><newstext></textarea>
                  <br><b>Ссылка (URL):</b>
                  <br><input type=text name=link size=80 value="<newslink>">
                  <br><b>Картинка (URL):</b>
                  <br><input type=text name=img size=80 value="<newsimg>">
                  <br><b>Администратор:</b>
                  <br><input type=text name=user size=80 value="<user>">
                  <br>
                  <br><input type=button name="save" value="Save" onClick="dothis('save');" style="cursor:hand">
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <br>
      </td>
    </tr>
~; 

# Template for "MORE INFO..."
$moretemplate=qq~   <a href="<link>" class="mbtxt" title="Читать дальше...">Подробнее<img src="/images/podr.gif" alt="" width="20" height="10" border="0"></a>~; 

# Template for images
$imgtemplate=qq~<a href="<link>"><img src="<img>" alt="Подробнее..." border="0"></a>~;   

$configmenu = qq~
              <tr>
                <td colspan=2>&nbsp</td>
              </tr>
              <tr>
                <td valign="middle" align="center">&middot;</td>
                <td><a class="blue" href="javascript:dothis('config');"><b>Настройки</b></a></td>
              </tr>
~;
1;
